### ISSUE TITLE
Installation doesn't work

### ISSUE THREAD

**Issue by dakshhmehta** [Doptor-zz/Doptor#1]
Hello,

Great for this cool CMS. I look forward to contribute and use it for my future projects. However, while trying  to get my hands on Doptor, the installation fails because of "CreateCategoriesTable class not found" - probably migration is missing.

I had dig into the migrations, and haven't found anything on it. So, I am bit worried how it is even trying to find this class.

Let me know if I am missing something.

Thanks,
Daksh

**Comment by dakshhmehta** [comment]
The issue is because of blank migration file at https://github.com/Doptor/Doptor/blob/master/app/components/posts/database/migrations/2014_01_28_153951_create_categories_table.php

**Comment by itsaafrin** [comment]
@dakshhmehta 

Thanks for pointing the error out. It was due to some missing files during the initial commit as those files are being re factored. Once the files are committed, it will be available for installation. Thanks for letting know on the issue. 

I will proceed closing this issue for now and update once the files are in the repository.

**Comment by itsaafrin** [comment]
@dakshhmehta 

The installation is fixed now. You may try it out and let know if there is any issue. ;)
